//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AZ_kampayler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AZ_kampayler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _10 {
            get {
                object obj = ResourceManager.GetObject("_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11 {
            get {
                object obj = ResourceManager.GetObject("_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _12 {
            get {
                object obj = ResourceManager.GetObject("_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _13 {
            get {
                object obj = ResourceManager.GetObject("_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _14 {
            get {
                object obj = ResourceManager.GetObject("_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _15 {
            get {
                object obj = ResourceManager.GetObject("_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _16 {
            get {
                object obj = ResourceManager.GetObject("_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _17 {
            get {
                object obj = ResourceManager.GetObject("_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _18 {
            get {
                object obj = ResourceManager.GetObject("_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _19 {
            get {
                object obj = ResourceManager.GetObject("_19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4 {
            get {
                object obj = ResourceManager.GetObject("_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5 {
            get {
                object obj = ResourceManager.GetObject("_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6 {
            get {
                object obj = ResourceManager.GetObject("_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7 {
            get {
                object obj = ResourceManager.GetObject("_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8 {
            get {
                object obj = ResourceManager.GetObject("_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9 {
            get {
                object obj = ResourceManager.GetObject("_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include&lt;iostream.h&gt;
        ///
        ///&lt;delimeters,#&gt;&lt;keyword,include&gt;&lt;delimeters,&lt; &gt;&lt;keyword,iostream.h&gt;&lt;delimeters,&gt; &gt;
        ///
        ///
        ///
        ///#include&lt;conio.h&gt;
        ///
        ///&lt;delimeters,#&gt;&lt;keyword,include&gt;&lt;delimeters,&lt; &gt;&lt;keyword,conio.h&gt;&lt;delimeters,&gt; &gt;
        ///
        ///
        ///
        ///
        ///int main () {
        ///
        ///&lt;keyword,int&gt;&lt;keyword,main&gt;&lt;delimeters,( &gt;&lt;delimeters,) &gt;&lt;delimeters,{ &gt;
        ///
        ///
        ///
        ///
        ///int a,b,c ;
        ///
        ///&lt;keyword,int&gt;&lt;id1,a&gt;&lt;delimeters, ,&gt;&lt;id2,b&gt;&lt;delimeters, ,&gt;&lt;id3,c&gt;&lt;delimeters, ;&gt;
        ///
        ///
        ///
        ///
        ///cout&lt;&lt;&quot;enter number a:&quot; ;
        ///
        ///&lt;keyword,cout&gt;&lt;delimeters,&lt;&lt; &gt;&lt;delimeters,&quot;&gt;&lt;std,enter num [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lexical_analyzer {
            get {
                return ResourceManager.GetString("lexical_analyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if (a*a==b*b+c*c)
        ///
        ///t4 = id1 * id2
        ///t3 = t2  * id3
        ///t2 = id4 + t1
        ///t4 = t3  * t2
        ///
        ///
        ///
        ///
        ///if (b*b==a*a+c*c)
        ///
        ///t4 = id1 * id2
        ///t3 = t2  * id3
        ///t2 = id4 + t1
        ///t4 = t3  * t2
        ///
        ///
        ///
        ///
        ///if (c*c==a*a+b*b)
        ///
        ///t4 = id1 * id2
        ///t3 = t2  * id3
        ///t2 = id4 + t1
        ///t4 = t3  * t2.
        /// </summary>
        internal static string optimization {
            get {
                return ResourceManager.GetString("optimization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cout &lt;&lt; &quot; enter number a: &quot; ;
        ///
        ///type ---&gt;cout
        ///STD :: &quot; enter number a &quot;
        ///
        ///
        ///
        ///
        ///
        ///cin &gt;&gt; a ;
        ///
        ///type ---&gt;cin
        ///E ---&gt; E,var | var
        ///var ---&gt; id
        ///
        ///
        ///
        ///
        ///
        ///cout &lt;&lt; &quot; enter number b: &quot; ;
        ///
        ///type ---&gt;cout
        ///STD :: &quot; enter number b &quot;
        ///
        ///
        ///
        ///
        ///
        ///cin &gt;&gt; b ;
        ///
        ///type ---&gt; cin
        ///E ---&gt; E,var | var
        ///var ---&gt; id
        ///
        ///
        ///
        ///
        ///
        ///cout &lt;&lt; &quot; enter number c: &quot; ;
        ///
        ///type ---&gt; cout
        ///STD :: &quot; enter number c &quot;
        ///
        ///
        ///
        ///
        ///
        ///cin &gt;&gt; c ;
        ///
        ///type ---&gt; cin
        ///E ---&gt; E,var | var
        ///var ---&gt; id
        ///
        ///
        ///
        ///
        ///
        ///if (a*a == b*b + c*c)
        ///
        ///type ---&gt; if
        ///E  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tahlil_nahvii {
            get {
                return ResourceManager.GetString("Tahlil_nahvii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if (a*a==a*b+c*c)
        ///
        ///t1=id5*id6
        ///t2=id4+t1
        ///t3=t2*id3
        ///t4=id1*id2
        ///
        ///
        ///
        ///
        ///
        ///else if (b*b==a*a+c*c) 
        ///
        ///t4=id1*id2
        ///t3=t2*id3
        ///t2=id4+t1
        ///t4=t3*t2
        ///
        ///
        ///
        ///
        ///
        ///else if (c*c==a*a+b*b)
        ///
        ///t1=id5*id6
        ///t2=id4+t1
        ///t3=t2*id3
        ///t4=id1*id2
        ///t3=t4.
        /// </summary>
        internal static string Tolid_code_mianii {
            get {
                return ResourceManager.GetString("Tolid_code_mianii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if (a*a==a*b+c*c)
        ///
        ///MOV  R3,id5
        ///MUL  id6.R3
        ///MOV  R2,id4
        ///MUL  R2,id3
        ///ADD  R2,R3
        ///MOV  id1,R1
        ///MUL  id2,R1
        ///MOV  R2,R1
        ///
        ///
        ///
        ///
        ///
        /// 
        ///else if (b*b==a*a+c*c)
        ///
        ///MOV  R3,id5
        ///MUL  R3,id6
        ///MOV  R2,id4
        ///MUL  R2,id3
        ///ADD  R2.R3
        ///MOV  R1,id1
        ///MUL  R1,id2
        ///mov  R1,R2
        ///
        ///
        ///
        ///
        ///
        ///
        ///else if (c*c==a*a+b*b)
        ///
        ///MOV  R3,id5
        ///MUL  R3,id6
        ///MOV  id4,R2
        ///MUL  R2,id3
        ///ADD  R2,R3
        ///MOV  R1,id2
        ///MUL  R1,id2
        ///MOV  R1,R2.
        /// </summary>
        internal static string Tolid_code_nahaii {
            get {
                return ResourceManager.GetString("Tolid_code_nahaii", resourceCulture);
            }
        }
    }
}
